### ISSUE TITLE
Mass Assignment Option

### ISSUE THREAD

**Issue by SDJeff** [geccomedia/weclapp#13]
You can add 

protected $guarded = [];

to all models so a mass assignment is possible.

**Comment by Tamrael** [comment]
If you want to do mass assignment please use [unguard](https://laravel.com/api/6.x/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.html#method_unguard) and [reguard](https://laravel.com/api/6.x/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.html#method_reguard)

You can do this like in this example code:
```
$customer = new \Geccomedia\Weclapp\Models\Customer();
\Geccomedia\Weclapp\Models\Customer::unguard();
$customer->fill(['partyType' => 'ORGANIZATION']);
\Geccomedia\Weclapp\Models\Customer::reguard();
```

We won't unguard all attributes because the guard is there for a reason (security)
