### ISSUE TITLE
SalesInvoice Dates

### ISSUE THREAD

**Issue by SDJeff** [geccomedia/weclapp#18]
Hi,

at Geccomedia\Weclapp\Model\SalesInvoice you are using $dates attribute bot not at the quotation or salesOrder model.
Is there any reason?

Which means that you have to you use different ways to import dates like the created date of the bill because weclapp needs the unix timestamp. So at the import of quotations and sales orders you have to convert it by yourself and at the salesInvoice you get a wrong date even if you set date by string YYYY-MM-DD or Create a Carbon Instance.

If if comment the protected $dates attribute and set the timestamp manually the creation of an invoice is correct.
If i set for example $weclappSalesInvoice->createdDate = '2020-04-19' or whatever, the date of the created invoice after $$weclappSalesInvoice->save() is every time  19.07.1970.

I think it will be necessary to set additionally:

` 
   /**
     * The storage format of the model's date columns.
     *
     * @var string
     */
    protected $dateFormat = 'U';
`

Finally is it possible to set this in a common way in each Model? What do you mean?

**Comment by Tamrael** [comment]
Hi,

let me get you some answers before I go and see what I can do to address the issues at hand:

> at Geccomedia\Weclapp\Model\SalesInvoice you are using $dates attribute bot not at the quotation or salesOrder model.
Is there any reason?

The only reason is that we don't use quotation or salesOrder at our company. The models where inserted as a batch but because weclapp doesn't provide a good resource on the model format (that I'm aware of, the documentation lists date-fields with an example value of 0...go figure)  we never added all the fields of all the models to their respective $date fields.

If you need more fields in the $dates variable you can either use your own models by [extending the base-model](https://github.com/geccomedia/weclapp#custom-models) or add a pull request. I simply don't have the time to go trough all 51 models and check each for date fields, sorry.

> Which means that you have to you use different ways to import dates like the created date of the bill because weclapp needs the unix timestamp. So at the import of quotations and sales orders you have to convert it by yourself and at the salesInvoice you get a wrong date even if you set date by string YYYY-MM-DD or Create a Carbon Instance.

weclapp doesn't use the unix timestamp, hey use the milli-second-epoch (unix timestamp with milli-seconds). There is a problem when setting the date by string. That will be fixed in the next release.

> If if comment the protected $dates attribute and set the timestamp manually the creation of an invoice is correct.

naturally, if you set the date timestamp manually without the build in date conversion of laravel that's expected.

> `/** * The storage format of the model's date columns. * * @var string */ protected $dateFormat = 'U';`
Finally is it possible to set this in a common way in each Model? What do you mean?

That was already present on the base model all the other models extend but as weclapp uses 'Uv' instead of 'U' I had to include a [very hacky way](https://github.com/geccomedia/weclapp/blob/a6faf3b9656503922e8e2d861640f43813bef45d/src/Model.php#L104) to format the date. Next release will be a little less hacky but since Laravel assumes an integer is ALWAYS unix timestamp and nothing else there is still a little hack needed.

**Comment by Tamrael** [comment]
@SDJeff I just released a fix for the date-conversion problems. Setting a date (has to be part of the $dates on the model) by string or carbon now yields the correct result.

Let me know if you can confirm this with v2.1.1

**Comment by SDJeff** [comment]
Yes. It runs. Great. Fast response.
Perhaps i can help you here with the repro. Are you based at Cologne? Is that right? We should have a call...
